image: node:alpine
variables:
  HUB_IMAGE_BASE: owings1/gameon

stages:
  - test
  - publish

test:
  stage: test
  tags:
    - docker
  script:
    - npm install
    - npm test

test_dist:
  stage: test
  when: manual
  tags:
    - docker
  before_script:
    - apk add git
  script:
    - npm install
    - npm run-script dist

test_docker:
  stage: test
  when: manual
  tags:
    - shell
  before_script:
    - export IMAGE_TAG=${HUB_IMAGE_BASE}:${CI_JOB_ID}
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
  script:
    - docker build -t "$IMAGE_TAG" .
    - docker rmi "$IMAGE_TAG"
  after_script:
    - docker logout

publish_s3:
  stage: publish
  only:
    - tags
    - /^v[0-9]+[0-9.]+$/
  tags:
    - docker
  before_script:
    - apk add git
  script:
    - npm install
    - npm run-script dist_and_publish

publish_docker:
  stage: publish
  only:
    - tags
    - /^v[0-9]+[0-9.]+$/
  tags:
    - shell
  before_script:
    - export IMAGE_TAG=${HUB_IMAGE_BASE}:${CI_COMMIT_TAG:1}
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
  script:
    - docker build -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"
    - docker rmi "$IMAGE_TAG"
  after_script:
    - docker logout