#!/bin/bash

set -e

if [[ -z "$IMAGE_NAME" ]]; then
    echo "IMAGE_NAME not set" >&2
    exit 1
fi

BASEDIR="$(cd `dirname $0`/.. && pwd)"
DOCKERFILE="$BASEDIR/Dockerfile"
TMPDIR="$BASEDIR/tmp"

echo "Preparing npmrc secret"
mkdir -p "$TMPDIR"
NPMRC="$TMPDIR/npmrc"
echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > "$NPMRC"

echo "Executing docker build"
set +e
DOCKER_BUILDKIT=1 docker build \
    -t "$IMAGE_NAME" \
    --secret id=npmrc,src="$NPMRC" \
    "$BASEDIR"

CODE="$?"

rm -f "$NPMRC"

if [[ "$CODE" != 0 ]]; then
    echo "Docker failed with exit code $CODE" >&2
fi

exit "$CODE"