name: dist

env:
  FORCE_COLOR: "1"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: macos-11
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm install
    - name: Compile messages
      run: npm run compile
    - name: Build tarballs
      run: npm run dist
    - name: Build MacOS installer
      run: npm run dist:mac
    - name: Upload tarballs to S3
      run: npm run publish
    - name: Upload MacOS installer to S3
      run: npm run publish:mac