name: dist

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: macos-11
    environment: dist
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run compile
    - run: npm run dist
    - run: npm run mac
    - run: npm run publish